# Generated by Django 4.1.2 on 2023-05-29 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('idA', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nombreArticulo', models.CharField(max_length=20)),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('fecha_producto', models.DateField()),
                ('activo', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Articulos',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_producto',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nombreArticulo',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='stock',
        ),
    ]
