# Generated by Django 4.1.2 on 2023-06-10 04:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_rename_nombrearticulo_articulo_articulo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='idA',
            new_name='articulo',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='idA',
        ),
        migrations.AddField(
            model_name='articulo',
            name='nombre_articulo',
            field=models.CharField(default=datetime.datetime(2023, 6, 10, 4, 15, 22, 767105, tzinfo=datetime.timezone.utc), max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articulo',
            name='articulo',
            field=models.AutoField(db_column='idArticulo', primary_key=True, serialize=False),
        ),
    ]
