# Generated by Django 4.1.2 on 2023-06-15 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_rename_id_cliente_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(default=datetime.datetime(2023, 6, 15, 18, 22, 41, 76091, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
    ]
