# Generated by Django 4.1.2 on 2023-06-18 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_cliente_direccion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='articulo',
            new_name='id_articulo',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='articulo',
            new_name='id_articulo',
        ),
    ]
